### PR TITLE
Use distroless as base image

### PR DESCRIPTION
**Pull request by jsafrane**

### CODE REVIEW

**Comment by jsafrane** [comment]
Reason: k8s core components move its base images to distroless/static. See kubernetes/kubernetes#70249 (comment) for details.

**Comment by davidz627** [comment]
have we done enough verification/testing to know that this works for us? i.e. core functionality works, can still get logs, etc.

**Comment by jsafrane** [comment]
I tested node-driver-registrat + attacher + provisioner with distroless, `kubectl logs` works as usual. `kubectl exec` obviously does not work, because there is no `/bin/sh` in the container.

I haven't tested the other containers (snapshotter, resizer, cluster-registrar, ...)

**Pull request merged**
