### PR TITLE
Errors from fetching secrets should be reported

### PR DESCRIPTION
**Pull request by wackxu**
fix https://github.com/kubernetes-csi/external-provisioner/issues/55
/assign @jsafrane

### CODE REVIEW

**Comment by pohly** [comment]
How does the report look like? I.e., can a developer who has misconfigured the secret understand what he did wrong?

Should this have a corresponding test somewhere? That might be a good place to show the expected error message and test for it at the same time.

**Comment by jsafrane** [comment]
lgtm, can you please rebase?

@pohly, error is going to be reported as event on the PVC, visible e.g. in `kubectl describe pvc`.

**Comment by pohly** [comment]
On Wed, 2018-03-14 at 15:55 +0000, Jan Šafránek wrote:
> @pohly, error is going to be reported as event on the PVC, visible
> e.g. in kubectl describe pvc.

That's where I'd expect it to show up. I was more wondering whether the
 error text is something that can be understood and traced back to the
root cause or whether it is something obscure.

**Comment by jsafrane** [comment]
the PR uses `failed to find the secret %s in the namespace %s with error: %v\n", secretName, nameSpace, err`

**Comment by wackxu** [comment]
@jsafrane Rebased, PTAL

**Comment by jsafrane** [comment]
thanks for the PR!

**Pull request merged**
