### PR TITLE
update csi-translation-lib dependency to include vSphere CSI Migration

### PR DESCRIPTION
**Pull request by divyenpatel**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR is adding support for vSphere CSI Migration in the external-provisioner by updating csi-translation-lib dependency.

 

**Special notes for your reviewer**:

```
make all
./release-tools/verify-go-version.sh "go"
mkdir -p bin
echo '' | tr ';' '\n' | while read -r os arch suffix; do \
		if ! (set -x; CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build  -a -ldflags '-X main.version=v1.6.0-67-g3cb95dfbe -extldflags "-static"' -o "./bin/csi-provisioner$suffix" ./cmd/csi-provisioner); then \
			echo "Building csi-provisioner for GOOS=$os GOARCH=$arch failed, see error(s) above."; \
			exit 1; \
		fi; \
	done
+ CGO_ENABLED=0
+ GOOS=
+ GOARCH=
+ go build -a -ldflags '-X main.version=v1.6.0-67-g3cb95dfbe -extldflags "-static"' -o ./bin/csi-provisioner ./cmd/csi-provisioner
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by divyenpatel** [comment]
cc: @xing-yang

**Comment by xing-yang** [comment]
Can you provide a link to that hash?

**Comment by xing-yang** [comment]
Can you do a "make" in your local repo?  Looks like there are still make errors.

**Comment by divyenpatel** [comment]
> Can you provide a link to that hash?

https://github.com/kubernetes/csi-translation-lib/commit/48562615b4e9adfd79339351e1d0ce4f51204a39

looks like there is a dependency change in the `csi-translation-lib` causing compilation issue.

> case-insensitive import collision: "github.com/googleapis/gnostic/openapiv2" and "github.com/googleapis/gnostic/OpenAPIv2"

**Comment by divyenpatel** [comment]
closing this PR. vendor dependency will get updated as part of pull 428

**Pull request closed without merging**
