### PR TITLE
Update prow to latest release-tools

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidz627** [comment]
Whats happening with the commits here. Are we not vendoring in release tools and cherry-picking them from a special branch or something?

**Comment by msau42** [comment]
We're using git subtree to "vendor" in release tools, since golang vendor doesn't work for non-.go files.  I'm following the instructions [here](https://github.com/kubernetes-csi/external-provisioner/blob/master/release-tools/README.md#sharing-and-updating)

**Pull request merged**
