### PR TITLE
Add changelog for v3.6

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add changelog for v3.6

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE

```

### CODE REVIEW

**Comment by xing-yang** [comment]
Looks like we are not mentioning any PR in the changelog:).  Should we add a brief release note at least in this PR https://github.com/kubernetes-csi/external-provisioner/pull/999 about deps update to K8s 1.28?  I know that we have not been consistent.  Some of these kind of deps update have release notes while others don't.  Maybe an update to a newer K8s minor version is worth mentioning in the release note?

**Comment by msau42** [comment]
@Sneha-at can you update the script to add a release note to the PR description similar to what I manually added in #999?

**Comment by msau42** [comment]
@xing-yang updated

**Pull request merged**
