### PR TITLE
fix: introduce /v5 module suffix for go.mod

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
changes the go.mod path to add /v5 so that go module is resolved properly

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Adds the /v5 suffix that was missed on previous releases so that the go.mod resolves properly

**Special notes for your reviewer**:

Opened as per request on https://kubernetes.slack.com/archives/C09QZFCE5/p1718782253879689

**Does this PR introduce a user-facing change?**:

```release-note
action required: go module path was changed to github.com/kubernetes-csi/external-provisioner/v5, adjust accordingly when importing in go
```

### CODE REVIEW

**Comment by jakobmoellerdev** [comment]
@msau42 I think https://github.com/kubernetes-csi/external-provisioner/blob/c66e140569df5ef776a1e16812422f63405f2d36/.prow.sh#L3 is problematic because it is both a go import path as well as a directory path and now these 2 diverge with the /v5 bump. I believe that release tooling uses it as a path in https://github.com/kubernetes-csi/external-provisioner/blob/e96448ac2fb9cd15e681bd697c632fc32e580450/release-tools/prow.sh#L1038 and as a go import in https://github.com/kubernetes-csi/external-provisioner/blob/e96448ac2fb9cd15e681bd697c632fc32e580450/release-tools/prow.sh#L977

Any preference on how to fix that?

**Comment by msau42** [comment]
@jakobmoellerdev What do you think of creating a new variable? Edits to release-tools need to be done in https://github.com/kubernetes-csi/csi-release-tools/blob/master/prow.sh? first and than imported here as a git submodule (instructions are in the repo)

**Comment by jakobmoellerdev** [comment]
@msau42 I would need a checkup on the tools PR so that we can unblock that.

**Comment by jakobmoellerdev** [comment]
@msau42 thanks to the adjustment in the release tooling this one is now good to go :+1:

**Comment by msau42** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
