### PR TITLE
Update external-snapshotter client version to v4.1.0

### PR DESCRIPTION
**Pull request by xinyanw409**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind cleanup

**What this PR does / why we need it**:
This PR updates snapshot dependency to v4/client.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update to use VolumeSnapshot v4/client
```

### CODE REVIEW

**Comment by xing-yang** [comment]
You need to run `go mod vendor` and `go mod tidy`.

**Comment by xinyanw409** [comment]
> You need to run `go mod vendor` and `go mod tidy`.
I've already run theses commands.

**Comment by xing-yang** [comment]
Take a look of the unit test failure.  Looks like it is still using v1beta1.

**Comment by xing-yang** [comment]
@xinyanw409 Can you rebase your PR?

**Review by Mshn1361 — APPROVED** [review]

**Pull request merged**
