### PR TITLE
Don't process PVCs for in-tree volumes

### PR DESCRIPTION
**Pull request by jsafrane**
If I understand [code in `ProvisionExt`](https://github.com/kubernetes-csi/external-provisioner/blob/3184db61ab93bbe588fff4a223bf23c49a5d5937/pkg/controller/controller.go#L374), PVCs that require migrated in-tree provisioner in their StorageClass have their `volume.beta.kubernetes.io/storage-provisioner` annotation set to **CSI driver name**.

Therefore we do not need the provisioner library to listen for PVCs with in-tree provisioner at all and save some (little) CPU in unrelated PVC processing. I keep the check in `ProvisionExt`, just in case.

@ddebroy, PTAL carefuly.

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
/assign @ddebroy @davidz627 
Will this work or does lib still need the option to check `storageclass.provisioner`?

**Comment by ddebroy** [comment]
The additionalProvisionerNames stuff is necessary to keep this check at https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/master/controller/controller.go#L1234 happy for migration scenarios.

Without populating additionalProvisionerNames, we end up with:
```
controller.go:1235] provision "default/podpvc" class "standard": unknown provisioner 
"kubernetes.io/gce-pd" requested in claim's StorageClass
```

We discussed this a bit at https://github.com/kubernetes-csi/external-provisioner/pull/341#issuecomment-531025966

**Comment by jsafrane** [comment]
I see. I reworked the PR to still pass additional provisioners to the lib, but rejecting PVCs in `ShouldProvision`. PTAL.

**Comment by jsafrane** [comment]
> var _ controller.Qualifier = &csiProvisioner{}


Good idea, added.

**Pull request merged**
