### PR TITLE
[release-2.1] Update github.com/kubernetes-csi/csi-lib-utils

### PR DESCRIPTION
**Pull request by ialidzhikov**
/sig storage
/kind bug

Part of https://github.com/kubernetes-csi/external-provisioner/issues/732

**Does this PR introduce a user-facing change?**:

```release-note
external-provisioner now exits without output about goroutines when it fails to connect to the CSI driver.
```

### CODE REVIEW

**Comment by pohly** [comment]
Looks like the release-2.1 branch was not prepared to work with Kubernetes 1.23. It's old and will soon be unsupported. Do you really need it to be updated?

**Comment by ialidzhikov** [comment]
We are still using external-provisioner@2.1.2. I would appreciate if it is possible to cut a new patch release from the release-2.1 branch that includes this PR. If it is not possible we have to consider update to external-provisioner@2.2.x.

**Comment by pohly** [comment]
Why can you not update to a newer release?

**Comment by ialidzhikov** [comment]
Ok, I will then update to 2.2.x when a fix containing https://github.com/kubernetes-csi/external-provisioner/pull/734 is cut (2.2.3).

**Pull request closed without merging**
