### PR TITLE
Remove provisioner argument, update README

### LINKED ISSUE #162: Remove provisioner argument
It causes confusion and there is no reason to set provisioner name differently than the driver name

### PR DESCRIPTION
**Pull request by jarrpa**
Resolves #162 

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by jarrpa** [comment]
@msau42 PTAL

**Comment by msau42** [comment]
We need to remember to add this to the release notes

**Comment by jarrpa** [comment]
@msau42 Who would be good to approve this PR?

**Pull request merged**
