### PR TITLE
mark Topology featuregate as GA

### PR DESCRIPTION
**Pull request by divyenpatel**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR is marking topology feature as GA

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-csi/external-provisioner/issues/514

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
mark Topology feature gate as GA
```

### CODE REVIEW

**Comment by davidz627** [comment]
🔥

**Comment by msau42** [comment]
/lgtm
/approve

Thanks for fixing this!

**Pull request merged**
