### PR TITLE
update kubernetes-sigs/sig-storage-lib-external-provisioner to fix #195

### LINKED ISSUE #195: PV Protection breaks deleting
If a user deletes a PV while it has a PVC with a pv protection finalizer the CSI never gets alerted to delete the volume when the pvc is deleted.

### PR DESCRIPTION
**Pull request by rmb938**
Fixes #195

### CODE REVIEW

**Comment by rmb938** [comment]
Thanks @msau42. Would it be possible to get a release and a new container image built with this change?

**Comment by msau42** [comment]
Can you do a cherry-pick to release-1.0 branch, and then we can cut a new patch release

**Comment by rmb938** [comment]
Sure

**Pull request merged**
