### PR TITLE
[WIP]use storageclass annotation to reference secret and its namespace. Get secret and pass into UserCredentials Create/DeleteVolume calls

### LINKED ISSUE #28: Need to pass UserCredentials in Create/Delete Image
Currently storage class doesn't have credentials API, external-provisioner passes everything into Parameters but not into UserCredentials.

This is a problem for certain volumes such as rbd. We currently use parameters to store [plaint text secret ](https://github.com/ceph/ceph-csi/pull/9/files#diff-49fd745d0c902dc8994627ea8be68fc5)to get around this issue. 

Ideally credentials should still be encoded as a K8S Secret. External provisioner needs a mechanism to get credentials from StorageClass, either through a special parameter, annotation, or new API fields, then passes these credentials into UserCredentials in CreateVolume and DeleteVolume calls.

thanks @sbezverk for his early investigation into this issue

### PR DESCRIPTION
**Pull request by rootfs**
fix #28 
will provide an example too

cc @jsafrane @sbezverk

### CODE REVIEW

**Comment by sbezverk** [comment]
@rootfs I have made similar change but with proposed change in the storageclass, first class Atrributes secretRefs. I guess you do not want to wait until the change gets accepted for storageclass?

**Comment by rootfs** [comment]
@sbezverk storageclass annotation can work without having to wait for api change. We at least have a working driver using current k8s release.

**Comment by rootfs** [comment]
also need to pass secret annotation to PVC, so when k8s CSI plugin calls NodePublishVolume, the secret can be passed into user credentials as well (this part needs k8s change).

Mark the PR as WIP.

**Comment by rootfs** [comment]
CSI plugin fix is at https://github.com/kubernetes/kubernetes/pull/58527

**Comment by rootfs** [comment]
per http://blog.kubernetes.io/2018/01/introducing-container-storage-interface.html, credentials are not supported in alpha. Closing.

**Pull request closed without merging**
