### PR TITLE
update vendor k8s to 1.11

### PR DESCRIPTION
**Pull request by wackxu**
I just bump the vendor k8s version to 1.11,  nothing else.

### CODE REVIEW

**Comment by vladimirvivien** [comment]
Please add description what is being done in this PR.  It's updating 7K files.

**Comment by wackxu** [comment]
@vladimirvivien Thanks for your review, I just bump the vendor k8s version to 1.11, nothing else.

**Comment by jingxu97** [comment]
can we merge this soon?

**Comment by xing-yang** [comment]
@wackxu The vendor k8s version is already higher than 1.11.  I think this can be closed now.

**Pull request closed without merging**
